### ISSUE TITLE
profiler这个功能在linux下不能用吗？

### ISSUE THREAD

**Issue by shenbingxiaolong** [NetEase/pomelo-admin-web#8]
我更改了pomelo中的pomelo-admin中的部分错误，可以返回给profiler数据，但是pomelo-admin-web控制台显示解析时发生错误，我不知道如何解决，打印也无效。

**Comment by cynron** [comment]
相关的模块很久没有更新了，应该是格式之类的都对不上了，后续会考虑继续支持的
